services:
  postgres:
    image: postgres:18
    container_name: invoice_manager_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: invoice_pass
      POSTGRES_DB: invoice_manager
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
